title: 'Maciej Olszewski @ Github'
email:
description: > # this means to ignore newlines until "baseurl:"
  My personal GitHub page
baseurl: ""
url: "http://github.maciejolszewski.com"
twitter_username: olszewskimaciek
github_username:  MaciejOlszewski


markdown: kramdown
highlighter: rouge
permalink: pretty

excerpt_separator: ""
